import './globals.css'
import { outfit } from './ui/fonts'

export const metadata = {
	title: 'Entertainment',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				suppressHydrationWarning={true}
				className={`${outfit.className} antialiased bg-[#0E0F1A] max-w-[120rem] flex flex-col items-center justify-center mx-auto`}
			>
				{children}
			</body>
		</html>
	)
}
