import { SearchProvider } from './context/SearchContext'
import './globals.css'
import { outfit } from './ui/fonts'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				suppressHydrationWarning={true}
				className={`${outfit.className} antialiased bg-[#0E0F1A]`}
			>
				<SearchProvider>{children}</SearchProvider>
			</body>
		</html>
	)
}
